### ISSUE TITLE
Prepare Darwin Core Hour #4 - preparations, establishmentMeans and extension building

### ISSUE THREAD

**Issue by pzermoglio** [VertNet/dwc-qa-manage#10]
It seemed obvious from the previous webinar (DwC Hour Chapter 2) that a webinar about preparations would be most welcome.
Andy Bentley, University of Kansas Fish Curator, has offered to give the webinar on this topic.

**Comment by debpaul** [comment]
Both Andy Bentley abentley@ku.edu and Quentin Groom @qgroom quentin.groom@plantentuinmeise.be have said yes to doing a joint dwc hour. Date / title to be decided. See email conversations. Topic will cover dwc:establishmentMeans and dwc:preparations. Scope is to cover concept of the birth of a new term, implementing it, noting any issues (and what next ideas) followed by the dwc:preparations data which seem to strongly indicate the need for an extension - so that process can be highlighted.

**Comment by tucotuco** [comment]
@tucotuco will provide Darwin Core Hour introduction and Brief Introduction about the theme that binds the two talks and why we are doing them together, which is the process of evolution of the standard for new terms and extensions

**Comment by tucotuco** [comment]
Presentations completely successfully.

**Comment by ekrimmel** [comment]
Gary reports that we had 64 total participants and 19 post-webinar survey respondents for this webinar.
